### PR TITLE
Ckan 2.8.6 merge

### PR DESCRIPTION
**Pull request by ThrawnCA**

### CODE REVIEW

**Comment by duttonw** [comment]
can we not just use the https://github.com/qld-gov-au/ckan/tree/qgov-master-2.8.6-rebased since this is our tiny changes rebased on top of 2.8.6 vs trying to merge in everything ontop of our work?

This keeps it clean and also means we can drop our changes once they are in the core etc.

**Comment by ThrawnCA** [comment]
> can we not just use the https://github.com/qld-gov-au/ckan/tree/qgov-master-2.8.6-rebased since this is our tiny changes rebased on top of 2.8.6 vs trying to merge in everything ontop of our work?
> 
> This keeps it clean and also means we can drop our changes once they are in the core etc.

Apart from commit history, is it much different in the end?

**Comment by duttonw** [comment]
if we remove the sqlalchemy stuff, then its very clean history vs hidden behind 87 commits.

**Comment by ThrawnCA** [comment]
> if we remove the sqlalchemy stuff, then its very clean history vs hidden behind 87 commits.

Those are mostly the original commits from core to go from 2.8.4 to 2.8.6. I think keeping them in the history makes sense.

**Comment by ThrawnCA** [comment]
Changing to branch per upstream tag.

**Pull request closed without merging**
